#!/bin/bash
# Date: 2016-03-06
# Author: YtRen <rytubuntulinux@gmail.com>
# Improve the html text convert by Minimalist Markdown Editor
# Usage: ./md2hlv4 html_text

sed -i '1 i\
<?xml version="1.0" encoding="utf-8"?>\
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"\
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\
<html xmlns="http://www.w3.org/1999/xhtml">' $1

sed -i '5a\
<div class="content" style="margin-left:5px;margin-right:5px;">' $1
sed -i '/^$/ d' $1
sed -i 's@<pre@<pre style="background-color:#EBEBEB;" @g' $1
