#!/bin/bash
#Date: 2015-09-13
#Last Update: 2015-10-22
#Author: YtRen <rytubuntulinux@gmail.com>
#Function:This shell script can make browser show Chinese correctly and convert markdown to
# html conveniently.
#Usage: md markdown_text html_text.html
if [ ! -e "html_text.html" ]
then
	echo '<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">'  > html_text.html
fi
sed -i '5,$ d' html_text.html
markdown ${1} >> html_text.html
sed -i '/^$/ d' html_text.html
sed -i 's@<p>@@' html_text.html
sed -i 's@</p>@@' html_text.html
